Repository sulu/SuluArticleBundle, pull requests merged in 2020-06, with the labels that each got.

#484 Remove installation instructions that are not necessary anymore
  Resources/doc/default.html.twig
  Resources/doc/installation.md
Labels: enhancement

#495 Use elasticsearch bundle fork
  Resources/doc/installation-es2.md
  Resources/doc/installation-es5.md
  composer.json
Labels: enhancement

#433 Add support for elasticsearch 7
  .circleci/config.yml
  .travis.yml
  README.md
  Resources/doc/installation.md
  composer.json
Labels: feature

#493 Fix elasticsearch error for no resource segment in page tree smart content
  Content/PageTreeArticleDataProvider.php
  Tests/Functional/Content/PageTreeArticleDataProviderTest.php
Labels: bug

#494 Fix pagination default limit for smart content
  Content/ArticleDataProvider.php
  Tests/Functional/Content/ArticleDataProviderTest.php
Labels: bug

#498 Remove template default type definition
  .travis.yml
  DependencyInjection/StructureValidatorCompilerPass.php
  DependencyInjection/SuluArticleExtension.php
  Resources/doc/installation.md
  Tests/Application/config/templates/articles/default_pages.xml
Labels: bug
