Repository sulu/SuluArticleBundle, pull requests merged in 2020-09, with the labels that each got.

#516 Fix backview for excerpt and settings
  Admin/ArticleAdmin.php
Labels: bug

#508 Add xliff export for articles
  Command/ArticleExportCommand.php
  Export/ArticleExport.php
  Export/ArticleExportInterface.php
  Export/ExportFormatNotFoundException.php
  Resources/config/services.xml
  Resources/doc/README.md
  Resources/doc/xliff.md
  Resources/views/Export/Article/1.2.xliff.twig
  Resources/views/Export/Article/base.export.twig
  Tests/Functional/Controller/ArticleControllerTest.php
  Tests/Functional/Export/ArticleExportTest.php
Labels: feature

#515 Add annotation reader to dynamically add the document annotation
  Document/ArticleViewDocument.php
  Elasticsearch/AnnotationReader.php
  Resources/config/services.xml
  Resources/doc/article-view-document.md
  Tests/Functional/Controller/ArticleControllerTest.php
  Tests/Functional/Controller/ArticlePageControllerTest.php
  Tests/Functional/Document/Index/ArticleIndexerTest.php
  Tests/TestExtendBundle/Document/ArticleViewDocument.php
  Tests/app/config/config_extend.yml
  composer.json
Labels: bug

#513 Remove default type fallback in compilerpass
  DependencyInjection/StructureValidatorCompilerPass.php
  composer.json
Labels: enhancement
